### ISSUE TITLE
Started getting error {"BadSecureChannelClosed"}

### ISSUE THREAD

**Issue by MikhailKrasnobaev** [hylasoft-usa/h-opc#15]
Good day,

I started getting this error when i'm trying to connect to our companies KepwareServerEx.
The interesting part is that when I reinitialize the server it works for some time.
The level of security on Kepware is set to None. And if understand this correctly the server and the client create ssl certificates automatically, so no certification issuing needs to be done.

Maybe a certificate is still needed?

**Comment by Tonny72** [comment]
What do get if you use another client?

**Comment by MikhailKrasnobaev** [comment]
The client from OPC foundation gives me the same error:

'EXCEPTION (ServiceResultException)
'BadSecureChannelClosed

**Comment by Tonny72** [comment]
Seems like a Kepware server issue. Maybe you drop your question there. 
This is a document I found
https://www.kepware.com/products/clientace/documents/configuring-secured-ua-communications-clientace/

**Comment by MikhailKrasnobaev** [comment]
I've already went through all the Kepware materials, found a more interesting place.
It turns out that OPC Foundation joind Github https://github.com/OPCFoundation 

Found info about the error here http://opcfoundation.github.io/UA-.NET/help/index.htm#getting_started.htm

If will post here the solution if there is one.

**Comment by MikhailKrasnobaev** [comment]
Turns out that OPC UA does not like ASP applications running on IIS.

**Comment by bklever** [comment]
Hi Mikhail, did you find a workaround to this problem? We have the exact same exception, with our platform built on asp.Net running on IIS. Would prefer not to switch over to DA..

**Comment by MikhailKrasnobaev** [comment]
Well, actually not. Even if I turn off all the certification control on the server, it still throws this error after some time. Only the re-initialization of the Kepware server helps for some time. 
This post gives a bit more info http://www.opclabs.com/forum/ua-connections/1309-ua-client-certificates , but I haven't tried it yet. In the next couple of weeks I will start to work with the Kepware support on this issue.

**Comment by jmbeach** [comment]
Can I close this issue? Did the problem ever get resolved?

**Comment by MikhailKrasnobaev** [comment]
Good day,

yes, turns out it is normal and the problem is between IIS and OPC UA.

**Comment by jmbeach** [comment]
Ah, I see.
