### ISSUE TITLE
I want to extend the da and ua client, but I can't.

### ISSUE THREAD

**Issue by parallelbgls** [hylasoft-usa/h-opc#16]
Because of the private Server or Session, I can't extend the class. Can you change the _server and _session to protected or implement a public getter. Thanks.
Actually, I want to get more imformation like quality and timestamp when I read the opcda value in my current project.

**Comment by jmbeach** [comment]
The da client and ua client are not a part of h-opc. h-opc utilizes those classes from OPC foundation libraries Opc.Ua.Client and OpcNetApi. I believe this should be closed.

**Comment by jmbeach** [comment]
7cd8ed3bf93e27cfd96d93ab2254860acd044eb8

**Comment by jmbeach** [comment]
Server is now protected int the DaClient class. Will do others later

**Comment by jmbeach** [comment]
Fixed this in the latest release.
