### ISSUE TITLE
h-opc-cli has no exit option

### ISSUE THREAD

**Issue by vchegwidden** [hylasoft-usa/h-opc#22]
There is no option in the cli to disconnect from the OPC server. Should I use Ctrl-C to exit the program?

Shouldn't there be code to call `Dispose` on the client object since the `IClient ` interface implements `IDisposable`?

**Comment by jmbeach** [comment]
As you can see in [this commit](https://github.com/hylasoft-usa/h-opc/commit/7746d074e9cbd5a2c83aacd365bb342c6de8a43a), I added the exit functionality (and many other things). Sorry, I didn't break that commit up.

You can download the CLI from the [release page](https://github.com/hylasoft-usa/h-opc/releases/tag/v0.7.1.1) now.
