### ISSUE TITLE
Get information from kepserverEx

### ISSUE THREAD

**Issue by pmout** [hylasoft-usa/h-opc#3]
I use command _client.FindNode("Channel1.Device1.DB91,W0[78]") to get information from kepclient to get word array of a PLC "connected" in kepserverEx.

It is possible to get same information from kepserverEx in h-opc?

**Comment by itajaja** [comment]
You said that your receive this error correct?

> The tag "DB91,W0[78]" doesn't exist on folder "Channel1.Device1"

can you try to do the following:

````
var nodes = client.FindNode("Channel1.Device1").SubNodes;
````

and then put a breakpoint and debug that line. The `nodes` variable should hold all the nodes under the "Channel1.Device1" folder

**Comment by pmout** [comment]
I get

[image: Inline image 1]

Pedro Moutinho.

**Comment by itajaja** [comment]
I don't see your image. Please attach the image through the github website and not through your email client :)

**Comment by pmout** [comment]
Sorry

![node](https://cloud.githubusercontent.com/assets/4228505/6045366/70301a3a-ac91-11e4-86c8-aca21c0c5fad.png)

**Comment by itajaja** [comment]
Well, it doesn't find that specific node you are looking for. Can you give me more information about that? Maybe the type of the node is not supported. If you could give me the details about the node taken from Kepex, that might help.

**Comment by pmout** [comment]
That values are the same I in Kepware.KEPServerEX.V5. It helps?

![kepclient](https://cloud.githubusercontent.com/assets/4228505/6045813/e628fd9e-ac94-11e4-9cd2-99a02d9bfe7a.png)

**Comment by pmout** [comment]
If I add a new group and in that group I add channel1.device1.DB91,W0[78] e get the correct information from PLC
![group](https://cloud.githubusercontent.com/assets/4228505/6045921/aa0ec590-ac95-11e4-937b-430b29274819.png)

**Comment by itajaja** [comment]
I'll try to install Kepex and see if I can debug it. Maybe the Word Array type is not supported yet by h-opc

**Comment by pmout** [comment]
Hi,
In EasyOpc.UA from OpcLabs I can get values using:
easyUAClient1.Read("opc.tcp://10.199.226.11:49320/",               "nsu=KEPServerEX;s=channel4.device1.DB91,W0[78]");

It helps?

**Comment by itajaja** [comment]
I tried to read arrays from my server and it gives no problems. Can you tried to download [this client](https://opcfoundation.org/developer-tools/developer-kits-unified-architecture/sample-applications) and run the gneric client? then can you take a screenshot of the nodes shown from there? Thanks!

**Comment by pmout** [comment]
I get exactly the same info that in your app.
![opc](https://cloud.githubusercontent.com/assets/4228505/6077415/811cc46e-ade6-11e4-8aaa-67b4f8908908.png)
 
The problem is where can I put node info "nsu=KEPServerEX;s=channel4.device1.DB91,W0[78]" to get node value?

**Comment by itajaja** [comment]
If you don't see it even with that client, they are probably not set up to be visible from an OPC UA client, but only from DA. Also I don't understand if you are talking about Channel1 or Channel4...

**Comment by pmout** [comment]
As I said before  I can read with other software. I'm reading for several
channels. But in kapserver channels an devices are not the most important.
The main thing is the s parameter. This is the value that kep send to
Siemens plc to retrieve the value it value.
Em 06/02/2015 10:02, "Giacomo Tagliabue" <notifications@github.com>
escreveu:

**Comment by itajaja** [comment]
I am sorry I don't know how to help you, if also the OPC Foundation sample client can't find that value. This project is based on the OPC Foundation llibrary, so I don't know if I will ever be able to read that value, if also the OPC Foundation sample client can't find it, especially if I don't have direct access to your environment it gets difficult. Sorry :(
