### ISSUE TITLE
Connect to a remote OPC DA server

### ISSUE THREAD

**Issue by echaparroampa** [hylasoft-usa/h-opc#36]
Hello, I'm trying to connect to an OPC DA Server installed on a remote computer, both computers are in the same network and I'm using the same user, but I just can't make the connection, any advice?
Thanks in advance.

**Comment by jmbeach** [comment]
This is more than likely a COM issue. Can you give me the type of error message you are getting?

**Comment by echaparroampa** [comment]
Hi again, and thanks for your help, I hope you can help me.

First, this is my configuration:
1. - Both computers are inside a network called "WORKGROUP".
2. - I'm using the SAME USER on both computers.
3. - I've disabled the firewall.
4. - I'm using "Graybox".
5. OPC DA server is named "W10opc", and I'm trying to connect from a computer named "W10opcd", so the commnand line arguments are: "da opcda://W10opc".
6. - I've configured the "COM security" this way:
- Access Permission: Total access for default users and also "everyone" and "annonymous logon" 
- Launch and Activation Permissions:Total access for default users and also "everyone" and "annonymous logon".

### This is the Error: 
h-opc-cli v0.8.1
An error occured when trying connecting to the server
The application ended unexpectedly.
Opc.ConnectFailedException: E_NETWORK_ERROR
Could not connect to server.

   at Opc.Server.Connect(URL url, ConnectData connectData)
   at Opc.Da.Server.Connect(URL url, ConnectData connectData)
   at Opc.Server.Connect()
   at Hylasoft.Opc.Da.DaClient.Connect() in C:\Files\h-opc-master\h-opc\Da\DaClient.cs:line 60
   at Hylasoft.Opc.Cli.Program.Initialize(String[] args) in C:\Files\h-opc-master\h-opc-cli\Program.cs:line 64
   at Hylasoft.Opc.Cli.Program.Main(String[] args) in C:\Files\h-opc-master\h-opc-cli\Program.cs:line 21
To file an issue, visit http://github.com/hylasoft-usa/h-opc/issues

**Comment by jmbeach** [comment]
One quick test for me. Can you get this to work directly on the machine?

**Comment by jmbeach** [comment]
I mean directly on the OPC server

**Comment by jmbeach** [comment]
This is how I connect to Graybox simulator from the command line locally:
![image](https://cloud.githubusercontent.com/assets/2680142/20314545/2f753e96-ab20-11e6-84d2-c5e01559c583.png)

I have a feeling that the URL you are connecting to is slightly wrong because it only specifies the server. The full URL is probably something more along the lines of: `opcda://W10opc/Grabox.Simulator`

**Comment by echaparroampa** [comment]
Yes sir, you're right!, I was writing the wrong URL, I'm really sorry for wasting your time.
All works fine now, thanks a lot.

**Comment by jmbeach** [comment]
No worries. Glad it's working
