### ISSUE TITLE
h-opc-cli Write fails in certain cases

### ISSUE THREAD

**Issue by JxbMemory** [hylasoft-usa/h-opc#42]
Static.Scalar: write Int32 2
An error occurred running the last command:
Invalid response from the server. (Response Status: BadTypeMismatch)

Why?

**Comment by jmbeach** [comment]
I added this exception to a recent release because the type cast failed but it didn't alert me. Check your OPC server and make sure the type is what you expect

**Comment by JxbMemory** [comment]
Opcua Server Address:
http://www.openopcua.org/download/Files/OpenOpcUaCoreServer_Windows_DemoSimulation.zip
The OPC Foundation provides a client that is available.
But the "h-opc-cli.exe" occurred an error.
Here are all the code：
C:\Work\h-opc-master\h-opc-cli\bin\Release>h-opc-cli.exe UA "opc.tcp://WIN-1QEPS5VB3GC:16664/OpenOpcUaCoreServer"
h-opc-cli v0.8.1

: ls
Server
Static
Dynamic
OpenOpcUaSystem

: cd Static

Static: ls
Scalar
Mandatory

Static: cd Scalar

Static.Scalar: Read Int32
0

Static.Scalar: Write Int32 1
An error occurred running the last command:
Invalid response from the server. (Response Status: BadTypeMismatch)

**Comment by JxbMemory** [comment]
Writing errors for OPC Server provided by the OPC Foundation will be the same.

C:\Work\h-opc-master\h-opc-cli\bin\Release>h-opc-cli.exe UA "opc.tcp://win-1qeps5vb3gc:51210/UA/SampleServer"
h-opc-cli v0.8.1

: ls
Server
Data
MemoryBuffers
Boilers

: cd Data

Data: ls
Static
Dynamic
Conditions

Data: cd Static

Data.Static: ls
Scalar
Array
UserScalar
UserArray
AnalogScalar
AnalogArray
MethodTest

Data.Static: cd Scalar

Data.Static.Scalar: read Int32Value
433643559

Data.Static.Scalar: write Int32Value 1
An error occurred running the last command:
Invalid response from the server. (Response Status: BadTypeMismatch)

**Comment by jmbeach** [comment]
So it's just writing then? This problem might just be with the CLI. I'll take a look

**Comment by jmbeach** [comment]
I've reproduced the error in the cli. I'll try and see what's actually happening.

**Comment by jmbeach** [comment]
Yeah, the problem is with the CLI, not with the library. 

It tries to write using type `object`

If I change the code in `Repl.cs` in the h-opc-cli library from

```
    private void Write(IList<string> args)
    {
      if (args.Count < 2)
        throw new BadCommandException();
      _client.Write<object>(GenerateRelativeTag(args[0]), args[1]);
    }
```

to

```
    private void Write(IList<string> args)
    {
      if (args.Count < 2)
        throw new BadCommandException();
      _client.Write<Int32>(GenerateRelativeTag(args[0]), Convert.ToInt32(args[1]));
    }
```

then the write works.

This exception actually comes from the OPC Foundation libraries and not the h-opc libraries.

I can look into a way around this

**Comment by JxbMemory** [comment]
Thank you very much.
Looking forward to your solution.

**Comment by jmbeach** [comment]
See the [latest release](https://github.com/hylasoft-usa/h-opc/releases/tag/v0.9.0)
