### ISSUE TITLE
Kepware v6  - BadNodeIdUnknown

### ISSUE THREAD

**Issue by MuckersMate** [hylasoft-usa/h-opc#44]
Can Monitor a tag from a Kepware v5 server fine using the h-opc-cli.

Trying to do the same from a Kepware v6 server, the "Sub.ApplyChanges(), UaClient.Monitor<T> method" raises a BadSubscriptionIdInvalidServiceResultException.

**Comment by jmbeach** [comment]
I'm reading from Kepware V6 right now. Need more info

**Comment by MuckersMate** [comment]
Kepware v5, run h-opc-cli with connection params supplied as command line arguments, read [node] and value returned.

Exactly the same, but specifying a Kepware v6 server, read [node], "Invalid response from the server (Response Status : BadNodeIdUnknown)

Sorry, misleading information given. Exception is raised by UaClient.CheckReturnvalue
`
    private void CheckReturnValue(StatusCode status)
    {
      if (!StatusCode.IsGood(status))
        **throw new OpcException(string.Format("Invalid response from the server. (Response Status: {0})",** status), status);
    }`

The status is BadNodeIdUnknown.

**Comment by MuckersMate** [comment]
The Kepware v6 is running in a virtualised environment if this is relevant?

**Comment by jmbeach** [comment]
Is this a simulation server?

**Comment by MuckersMate** [comment]
No, it's using Allen Bradley drivers with actual PLCs connected. It is running in Demo Mode though...

**Comment by jmbeach** [comment]
Let's continue this here: https://gitter.im/H-Opc/H-Opc-CLI

**Comment by MuckersMate** [comment]
Actually, this is a false alarm - our client had assured us the Kepware server was actually out of its demonstration mode and activated (they couldn't see a countdown in the caption). It wasn't activated and the demo period had expired. Looks like Kepware 6 doesn't maintain the countdown in its caption...
Sorry, but thanks for your help!

**Comment by jmbeach** [comment]
No problem. Glad you got it fixed
