### ISSUE TITLE
UaClient - Datachange notifications stop

### ISSUE THREAD

**Issue by MuckersMate** [hylasoft-usa/h-opc#45]
On one of our test environments (Virtualised Windows 7), our UA Client stops receiving datachange notifications a short while (sometimes immediately) after adding an item to a Subscription. The AddItem code is shown below:

`      

        public T AddItem<T>(long subscriptionHandle, long tagID, string tag, Action<T, T, T, bool, Action> callback)
        {
            //
            // Find node (read from cache or create
            var node = FindNode(tag);

            //
            // Find subscription (group referenced by subscriptionHandle)
            var sub = FindSubscription(subscriptionHandle);

            try
            {

                if (sub == null)
                {

                    sub = new Subscription
                    {
                        PublishingInterval = _options.DefaultMonitorInterval,
                        PublishingEnabled = true,
                        DisplayName = tag,
                        Priority = byte.MaxValue,
                        Handle = subscriptionHandle
                    };
                    _session.AddSubscription(sub);
                    sub.Create();
                }

                //
                // Need to allocate a client handle
                if (tagID < 0)
                {
                    if (sub.MonitoredItems.Count() > 0)
                    {
                        //
                        // Take next number 
                        tagID = (long)sub.MonitoredItems.Max(i => i.Handle) + 1;
                    }
                    else
                    {
                        tagID = 0;
                    }
                }

                //
                // Item already monitored?
                var item = sub.MonitoredItems.FirstOrDefault(m => (long)m.Handle == tagID);
                try
                {
                    if (item == null)
                    {
                        item = new MonitoredItem
                        {
                            StartNodeId = node.NodeId,
                            AttributeId = Attributes.Value,
                            DisplayName = tag,
                            SamplingInterval = _options.DefaultMonitorInterval,
                            Handle = tagID
                        };
                     
                        sub.AddItem(item);
                       
                        sub.ApplyChanges();

                        item.Notification += (monitoredItem, args) =>
                        {
                            var p = (MonitoredItemNotification)args.NotificationValue;
                            var t = p.Value.WrappedValue.Value;

                            var ID = monitoredItem.Handle;
                            
                            Action unsubscribe = () =>
                            {
                                try
                                {
                                    sub.RemoveItems(new List<MonitoredItem>() {item});
                                }
                                catch (Exception ex)
                                {
                                    LogMessage(String.Format("Subscription End Failed for Tag : {0}", tag), ex);
                                }
                            };
                            
                            //
                            // Send back value, groupid, tag id, tag quality (good), unsunscribe callback
                            callback((T)t, (T)monitoredItem.Subscription.Handle, (T)ID, CheckReturnValue(p.Value.StatusCode), unsubscribe);
                        };
                    }
                }
                catch (Exception ex)
                {
                     LogMessage(String.Format("AddItem Failed (B) For Tag : {0}", tag), ex);
                }
                return (T)(object)item;
            }
            catch (Exception ex)
            {
                LogMessage(String.Format("AddItem Failed (C) For  Tag : {0}", tag), ex);
            }
            return default(T);
        }`

I've placed debug code (i.e. writing to a file) in the DataChange event and the Node definitely stops broadcasting a change. Similar debug code was placed on the unsubscribe, but it is not called. It only happens on this one PC (so far). We intend to deploy this to a wide range of clients so this is a bit concerning.

Can someone please shed any light on what may be causing the notifications to stop?

**Comment by MuckersMate** [comment]
Could this be a duplicate of https://github.com/hylasoft-usa/h-opc/issues/40

**Comment by jmbeach** [comment]
I think it is. Do you mind moving your comments over to there and we can close this issue?
