### ISSUE TITLE
ReadAsyncOPC

### ISSUE THREAD

**Issue by michailanatger** [hylasoft-usa/h-opc#60]
How i can read async from OPC?
my code is bad((
 var clientOPC = (Hylasoft.Opc.Da.DaClient)Session["clientOPC"];
 var floatNumber = clientOPC.ReadAsync<float>(@"Path\Number");
 floatNumber .Wait();
this is dont work, i am do this is on 4,0 framework

**Comment by jmbeach** [comment]
Take a look at [the DA tests](https://github.com/hylasoft-usa/h-opc/blob/master/tests/DaTest.cs#LC52) for examples.

The `ReadAsync` method returns a task. task.Result is the floating point number. However, if you call task.Wait(), you're defeating the purpose of using an asynchronous method and you should just use the regular `Read` method.

**Comment by jmbeach** [comment]
Also, h-opc is built against .NET Framework **4.5** so you cannot use 4.0. You might find a way to manually complie h-opc in .NET 4.0, but it is not supported.

**Comment by michailanatger** [comment]
all work on 4,0 framework and simple read work, but for me interesting method ReadAsync, I can not return value
var val= readAsync<T>("Path/number").Result. 
Or can not use ReadAsync<T>("Path/number").Start(); and another method. I am testing on 4.0 and 4.5

**Comment by jmbeach** [comment]
the code you want looks like this:

```
var task = _client.ReadAsync<float>("Path/number");
task.Wait();
var val = task.Result
```

**Comment by michailanatger** [comment]
i am tryed this is method, dont work how and another method readAsync((  With the holiday of the programmer and interesting projects and successful releases for you!!)))
