### ISSUE TITLE
failed to connect to opcda://localhost/OPCServer.WinCC

### ISSUE THREAD

**Issue by militiaonly** [hylasoft-usa/h-opc#62]
I can successfully connect to local Kepware OPC Server with the h-opc-cli
`h-opc-cli.exe da opcda://localhost/Kepware.KEPServerEX.V6`

However, when I am trying to connect to a Siemens WinCC V7.3 OPC DA Server (OPC Data Access 2.0), I got the below exception.
`h-opc-cli.exe da opcda://localhost/OPCServer.WinCC`
`h-opc-cli v0.9.0
An error occured when trying connecting to the server
The application ended unexpectedly.
System.Runtime.InteropServices.ExternalException (0x80004005): CoCreateInstanceEx: The specified service does not exist as an installed service.`

I am pretty sure that the WinCC OPC Server is working normally. Because I can use Prosys OPC Client to connect to it and browse and monitor tag values.

Is it a bug or is there some way to connect to a WinCC V7.3 OPC DA Server?
Many thanks in advance!

**Comment by jmbeach** [comment]
I don't have wincc installed, so I'm not sure. However, some things to try:

- Ensure `OPCServer.WinCC` is the right endpoint
- Make sure the WinCC opc server service is running
- Make sure opc enum service is running
- Check which user the service runs as and make sure you're logged in as the same user

DCOM is really tricky. It could be an issue with h.opc, but there's many configuration settings that can cause issues.

If none of this helps, you can clone h-opc and try to debug it on connection. Maybe the issue will be clear.

**Comment by militiaonly** [comment]
@jmbeach Thanks for your input. I will double check all the settings. But I think in my test there should not be any DCOM issue. Because both the server and client are in the same "localhost" windows 10 OS. Later I will publish more test results.

**Comment by militiaonly** [comment]
some testing screenshot with WinCC OPC Server.

-

**Comment by militiaonly** [comment]
The first image is that Prosys OPC Client can successfully connect and read tags from localhost OPCServer.WinCC.

The second image shows the error when use h-opc-cli to connect the same OPCServer.WinCC

<a href="https://ibb.co/eAD2Qw"><img src="https://preview.ibb.co/bTBp5w/1_prosys_opc.png" alt="1_prosys_opc" border="0"></a>
<a href="https://ibb.co/m67kdG"><img src="https://preview.ibb.co/eQtfCb/2_h_opc_cli.png" alt="2_h_opc_cli" border="0"></a><br /><a target='_blank' href='https://zh-cn.imgbb.com/'>image uploader</a><br />

**Comment by jmbeach** [comment]
One thing I notice about this is that Prosys does not list Kepware in the available clients.

**Comment by militiaonly** [comment]
@jmbeach Kepware is not installed in this VMWare VM. Only WinCC is installed. So there is no Kepware listed. The Prosys works fine with Kepware.

**Comment by militiaonly** [comment]
Hi Guys,
Today I reinstalled a brand new WinCC V7.4 SP1 in a clean Windows 7 Pro 64bits VMware VM.
And it seems that H-OPC works perfectly with OPCServer.WinCC. So I will close this issue.
@jmbeach Thank you for your suggestion.

**Comment by jmbeach** [comment]
@militiaonly Glad to hear that. If you find that there is a specific configuration of WinCC that can cause issues, let me know
