### ISSUE TITLE
Auto detection of OPC UA Server using H-opc client

### ISSUE THREAD

**Issue by MrPoudel** [hylasoft-usa/h-opc#71]
Hi @jmbeach,

Currently, I'm using the H-Opc library to connect to the OPC UA server( that is running on the raspberry pi).

My requirement is very simple: If I disconnect the device( in my case raspberrypi hosting a OPC UA server) from the network it should immediately detect the disconnection. When I connect the device back to the network it should detect the device immediately.

It is working but very slow. I tried different values of the 'SessionTimeout' but was not successful. It takes almost 10 seconds to connect to the server once I connect the raspberry pi to the network. Similarly, it takes the same amount of time if I unplug the raspberry pi from the network. Here is my code for one client:

            using (var client1 = new UaClient(new Uri("opc.tcp://raspberrypi-mounting.local:16664"))) 
                {                                   
                    client1.Options.ApplicationName = "Mounting-Client";
                    client1.Options.SessionName = "Mounting-session";         
                         
                    while (true)
                    {
                        client1.Options.SessionTimeout = 4000U;
                      
                        try
                        {                           
                           client1.Connect();
                         
                          // if a connection is successful, I will show the picture in GUI with green color
                           worker1.ReportProgress(1);                         
                           
                           while (true)
                           {                           
                              // Continuously check the status, if disconnected try again to connect
                               if (client1.Status == OpcStatus.NotConnected)
                               {                          
                                   
                               // if I disconnect the device having OPC UA server, 
                               //I will show the picture in GUI with red color
                                   worker1.ReportProgress(0);                                  
                                   break;
                               }
                           }
                                               
                        }

                        catch (Exception ex)
                        {
                           // if a connection is not successful, I will show the picture in GUI with red color                            
                            worker1.ReportProgress(0);
                            System.Console.WriteLine("Exception occured in Client1 ");
                            
                        }
                       
                        client1.Dispose();

                   }              
               
                }     

Are there some parameters that I can configure for the fast detection of connection and disconnection to the OPC UA server? Your help would be appreciated!

**Comment by jmbeach** [comment]
I think you might want to use [System.Threading.Timer](https://msdn.microsoft.com/en-us/library/system.threading.timer(v=vs.110).aspx) instead of `while(true)`. I think `while(true)` is going to overload the thread that your program is working on and actually slow things down.

Also, the nested `while(true)` is not actually doing anything because of the `break` statement. Example:

![image](https://user-images.githubusercontent.com/2680142/35041924-1f6dcb08-fb4c-11e7-88c9-6f779bd215d3.png)

VS:

![image](https://user-images.githubusercontent.com/2680142/35041950-3f5a8c9e-fb4c-11e7-9b08-b27a52c1ab4c.png)

so I would take the code out of the nested while.

Another thing is that you are disposing your client every loop. I would not dispose unless the program is exiting, but there is no need to do this because the `using` statement will automatically dispose the client.

so you'll have some code like the following:

```
using (var client1 = new UaClient(new Uri("opc.tcp://raspberrypi-mounting.local:16664")))
{
    var timerCheckConnection = new System.Threading.Timer(
        TimerCheckConnection_Tick, // event handler
        client1, // pass the client to the timer tick event
        0, // milliseconds before executing first timer tick (start immediately)
        250);
    Console.ReadLine(); // keep program alive
}

void TimerCheckConnection_Tick(object client)
{
    ((UaClient)client).Options.ApplicationName = "Mounting-Client";
    ((UaClient)client).Options.SessionName = "Mounting-session";         
    ((UaClient)client).Options.SessionTimeout = 4000U;
    try
    {
        ((DaClient)client).Connect();
        worker1.ReportProgress(1);                         
                  
        // Continuously check the status, if disconnected try again to connect
        if (((DaClient)client).Status == OpcStatus.NotConnected)
        {
            worker1.ReportProgress(0);                                  
        }
    }
    catch (Exception ex)
    {
        // if a connection is not successful, I will show the picture in GUI with red color                            
        worker1.ReportProgress(0);
        System.Console.WriteLine("Exception occured in Client1");                
    }
}
```
