### ISSUE TITLE
Unable to connect to DA Server

### ISSUE THREAD

**Issue by cpipero** [hylasoft-usa/h-opc#8]
Love the implementation. I wanted to test against KepwareEx via DA.
I tried to pass both:
"opcda://Kepware.KEPServerEX.V5"
or just "Kepware.KEPServerEX.V5"

But it always throws an exception, even with the command line utility h-opc-cli.

Thanks for any advice
Cos

**Comment by itajaja** [comment]
Hey @cpipero, thanks for the interest! I suggest you two things:

1. Copy and paste the stack trace of the error here, along with other useful information
1. clone the repository and debug it yourself

Also, are you on Windows 8? There are some known authorization issues with COM and Windows 8

**Comment by itajaja** [comment]
also, I see you put the name of the server, but not the name of the host. If the server is on the same machine, you can try

    opcda://localhost/Kepware.KEPServerEX.V5

if it's on another machine, try

    opcda://[IP ADDRESS]/Kepware.KEPServerEX.V5

If you want, you can paste the information of your server so I can double check you put the right info :)

**Comment by cpipero** [comment]
what a noob... that was it, I was testing the UA connection with the hostname and did not put it in the DA uri. Sorry.
That fixed it:
`opcda://localhost/Kepware.KEPServerEX.V5`
Thanks again
